# Whether file logging should be enabled.
#
# Disabling file logging can come with a slight performance improvement.
FILE_LOGGING_ENABLED=true

# Whether logging should be enabled altogether.
LOGGING_ENABLED=true

# Directory containing logs generated by `logger.sh`
LOG_DIR="$TMP_DIR/logs"
mkdir -p "$LOG_DIR"

# The path to the log file for the current day
LOG_FILE="$LOG_DIR/scripts.log"
