#!/usr/bin/env bash

source ~/.config/tpaau-17DB/scripts/include/paths.sh
source $LIB_DIR/notifications.sh
source $LIB_DIR/logger.sh
source $LIB_DIR/icons.sh

# Notify
notify_user() 
{
    raw_brightness=$(brightnessctl g)
    max_brightness=$(brightnessctl m)
    brightness_percentage=$((raw_brightness * 100 / max_brightness))

	icon_path=""
	if [[ $brightness_percentage -lt 33 ]]; then
		icon_path="$ICON_BRIGHTNESS_EMPTY"
	elif [[ $brightness_percentage -ge 33 ]] && [[ $brightness_percentage -le 66 ]]; then
		icon_path="$ICON_BRIGHTNESS_HALF"
	elif [[ $brightness_percentage -gt 66 ]]; then
		icon_path="$ICON_BRIGHTNESS_FULL"
	fi

    notify-send -i "$icon_path" -h string:x-canonical-private-synchronous:sys-notify -u low "Brightness: ${brightness_percentage}%" 
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && notify_user
}

# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_backlight
	exit 0
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
	exit 0
else
    raw_brightness=$(brightnessctl g)
    max_brightness=$(brightnessctl m)
    brightness_percentage=$((raw_brightness * 100 / max_brightness))
	echo $brightness_percentage
fi
